# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Packages

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/DiadromSW/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NPK_TOKEN}}
    - name: Build DoipCommunication
      run: dotnet build --configuration Release ./DiagCom.LocalCommunication/DiagCom.LocalCommunication.csproj
    - name: Publish the DoipCommunication package to GPR
      run: dotnet nuget push ./DiagCom.LocalCommunication/bin/Release/*.nupkg
    - name: Build Doip
      run: dotnet build --configuration Release ./DiagCom.Doip/DiagCom.Doip.csproj
    - name: Publish the Doip package to GPR
      run: dotnet nuget push ./DiagCom.LocalCommunication/bin/Release/*.nupkg
    - name: Build Uds
      run: dotnet build --configuration Release ./DiagCom.Uds/DiagCom.Uds.csproj
    - name: Publish the Uds package to GPR
      run: dotnet nuget push ./DiagCom.Uds/bin/Release/*.nupkg
    - name: Build Commands
      run: dotnet build --configuration Release ./DiagCom.Commands/DiagCom.Commands.csproj
    - name: Publish the Commands package to GPR
      run: dotnet nuget push ./DiagCom.Commands/bin/Release/*.nupkg
    - name: Build Logging
      run: dotnet build --configuration Release ./Logging/DiagCom.Logging.csproj
    - name: Publish the Logging package to GPR
      run: dotnet nuget push ./Logging/bin/Release/*.nupkg
    - name: Build Utilities
      run: dotnet build --configuration Release ./Utilities/DiagCom.Utilities.csproj
    - name: Publish the Utilities package to GPR
      run: dotnet nuget push ./Utilities/bin/Release/*.nupkg