name: NDS/DiadromSW.DiagDoipCom
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: NuGet tool installer
      uses: nuget/setup-nuget@v1.2.0
    - name: NuGet restore
      run: nuget restore DiagCom.sln
    - name: install msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: run msbuild
      run: msbuild DiagCom.sln -nowarn:CS1591;CA1416 -p:Configuration=DiagCom -p:Platform="x86"
